### PR TITLE
Add patterns test

### PR DESCRIPTION
**Pull request by RRozak**

### CODE REVIEW

**Comment by RRozak** [comment]
It is blocked by https://github.com/chipsalliance/Surelog/issues/1528

**Comment by RRozak** [comment]
It waits for https://github.com/antmicro/verilator/pull/412

**Review by rkapuscik — APPROVED** [review]
Looking good so far.

How about adding the example `assign o = '{8:1};` from https://github.com/chipsalliance/Surelog/issues/1528 here as well, to make sure it is handled properly now?

**Comment by RRozak** [comment]
Thank you.
That test will give warning or error, because index 8 is out of range.

**Review by rkapuscik — APPROVED** [review]

**Pull request merged**
