### PR TITLE
Add ImportTypeOfPort test

### PR DESCRIPTION
**Pull request by RRozak**

### CODE REVIEW

**Comment by RRozak** [comment]
ImportedParameter test works.

**Review by rkapuscik — APPROVED** [review]

**Comment by RRozak** [comment]
ImportParametrizedTypeAndDeclareParamWithTheSameName test waits for https://github.com/chipsalliance/Surelog/issues/2177

**Comment by RRozak** [comment]
Maybe the problem with ImportTypeOfPort can be fixed in Verilator, but I think it will be solved by chipsalliance/Surelog#2177 or change after that issue. I will wait with it until it is solved.

**Comment by RRozak** [comment]
ImportTypeOfPort still doesn't work. I will later look at it.

**Pull request merged**
